### ISSUE TITLE
Slow Refresh After Save

### ISSUE THREAD

**Issue by DClark5218** [alexgaribay/meteor-react-demo#1]
Hey, just tried out your stuff. Thanks a bunch! It's great to help me start to understand meteor.

Problem I am having is that the code is taking forever to recompile on my machine after save. >1 min. Anything I can get rid of to speed things up?

Thanks!

**Comment by alexgaribay** [comment]
From what I've read, recompiles take longer due to having some dependencies on packages from NPM. However, I don't think that they should add an extra minute on recompile.

**Comment by alexgaribay** [comment]
This should be working better now that react router is added as a package.
